version: '2'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "8000:15672"

  front:
    container_name: "front"
    env_file: front-app/.env
    restart: always
    build: ./front-app
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  worker1:
    container_name: "worker1"
    restart: always
    build: ./worker
    depends_on:
      - rabbitmq
      - browser
    links:
      - rabbitmq
      - browser

  worker2:
    container_name: "worker2"
    restart: always
    build: ./worker
    depends_on:
      - rabbitmq
      - browser
    links:
      - rabbitmq
      - browser

  browser:
    container_name: "browser"
    restart: always
    build: ./browser
    ports:
      - "3000:3000"